title: My Blog
description: A blog built with Jekyll and GitHub Pages
baseurl: "/blogon" # Leave empty for username.github.io, or "/my-blog" for project sites
url: "https://s41r4j.github.io/" # Replace with your GitHub Pages URL

markdown: kramdown
permalink: pretty
